import "./globals.css";
import Header from "@/components/Header";
import ThemeCom from "@/components/ThemeCom";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeCom>
            <Header />
            {children}
          </ThemeCom>
        </body>
      </html>
    </ClerkProvider>
  );
}
